version: "3.8"
services:
  db:
    image: postgres
    environment:
      DATABASE_ADMIN_USERNAME: admin
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
